# Site settings
title: Event Gone Good Blog
header-img: img/home-bg.jpg
email: dru@drusellers.com
description: > # this means to ignore newlines until "baseurl:"
  The blog of the fine people at Event Gone Good. Loaded with topics on
  technology, crossfit and the startup culture.
baseurl: ""
url: "http://eventgonegood.com"
twitter_username: drusellers
github_username:  drusellers
facebook_username:  drusellers

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems:
- jekyll-compass
- jekyll-paginate
